
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/my-next-project:cached
    working_dir: /my-next-project
    ports:
      - "3000:3000"
    command: /bin/bash /my-next-project/.devcontainer/scripts/startup.sh